[package]
name = "injector"
version = "0.1.0"
edition = "2021"

[build]
target-dir = "./bruh"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.26.1"
clap = { version = "3.2.20", features = ["derive"] }